# Generated by Django 6.1.2 on 2026-10-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category', models.CharField(choices=[('training', 'Training'), ('seminar', 'Seminar'), ('presentation', 'Presentation'), ('meeting', 'Meeting'), ('product_education', 'Product Education'), ('other', 'Other')], default='training', max_length=40)),
                ('short_summary', models.CharField(max_length=260)),
                ('full_details', models.TextField(blank=True)),
                ('flyer', models.ImageField(blank=True, null=True, upload_to='events/flyers/')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=250)),
                ('event_format', models.CharField(choices=[('physical', 'Physical'), ('online', 'Online'), ('both', 'Physical & Online')], default='both', max_length=20)),
                ('host_name', models.CharField(blank=True, max_length=180)),
                ('meeting_platform', models.CharField(blank=True, max_length=100)),
                ('meeting_link', models.URLField(blank=True)),
                ('meeting_code', models.CharField(blank=True, max_length=120)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'event_date', 'event_time'],
            },
        ),
    ]
