# Generated by Django 6.1.2 on 2026-10-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_title', models.CharField(blank=True, max_length=150)),
                ('testimonial_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='testimonials/audio/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='testimonials/thumbnails/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
