# Generated by Django 6.1.2 on 2026-10-07 17:59

import django.core.validators
import testimonials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/images/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='testimonials/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov']), testimonials.models.validate_testimonial_file_size]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='testimonials/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'm4a', 'ogg']), testimonials.models.validate_testimonial_file_size]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('audio', 'Audio')], max_length=20),
        ),
    ]
