# Generated by Django 6.1.2 on 2026-10-07 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptInCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('headline', models.CharField(max_length=220)),
                ('supporting_text', models.TextField(blank=True)),
                ('resource_title', models.CharField(max_length=180)),
                ('resource_description', models.TextField(blank=True)),
                ('resource_image', models.ImageField(blank=True, null=True, upload_to='optin/images/')),
                ('resource_file', models.FileField(blank=True, null=True, upload_to='optin/resources/')),
                ('button_text', models.CharField(default='Unlock Free Resource', max_length=100)),
                ('privacy_note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptInSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted')], default='new', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='leads.optincampaign')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
