# Generated by Django 6.1.2 on 2026-10-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optinsubmission',
            name='last_accessed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='optinsubmission',
            name='normalized_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='optinsubmission',
            name='normalized_phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
