# Generated by Django 6.1.2 on 2026-10-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_optinsubmission_last_accessed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optinsubmission',
            name='normalized_phone',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
